### ISSUE TITLE
Found module delegate error

### ISSUE THREAD

**Issue by alifjamaluddin** [grocer/grocer#103]
I found this error when sending a push notification.

``` ruby
Module::DelegationError (ActionController::RackDelegation#content_type delegated to @_response.content_type, but @_response is nil: #"text/html"}, @_status=200, @_request=nil, @_response=nil, @_db_runtime=25.278000000000006>):

app/controllers/api/v1/notifications_controller.rb:47:in `block in push'

app/controllers/api/v1/notifications_controller.rb:29:in `push'

app/controllers/api/v1/answers_controller.rb:38:in `create'

Rendered /Library/Ruby/Gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.8ms)

Rendered /Library/Ruby/Gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.2ms)

Rendered /Library/Ruby/Gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)

Rendered /Library/Ruby/Gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (18.3ms) 
```

Please advice me on this.

**Comment by stevenharman** [comment]
This backtrace looks like the problem is in your `NotificationsController#create` rather than in `Grocer`. Is this happening in a test?

**Comment by alifjamaluddin** [comment]
I'm not write any test for that notifications controller yet. Do I need to write it? Is the error related to the test?

This is the method I used to do push notification.

```ruby
def push(a,b,c)
	devices = Device.where(:user_id => b)
	devices.each do |device|
	
	pusher = Grocer.pusher(certificate: "#{Rails.root}/lib/PUSHNOTICERT.pem", # required
	                       passphrase:  "megasap1",                         # optional
	                       gateway:     "gateway.sandbox.push.apple.com", # optional
	                       port:        2195,                             #optional
	                       retries:     3)

	feedback = Grocer.feedback( certificate: "#{Rails.root}/lib/SLPushNotifDevCertAndKeys.pem", 
	                                  passphrase:  "megasap1",                        
	                                  gateway:     "feedback.sandbox.push.apple.com", 
	                                  port:        2196,                     
	                                  retries:     3)

	# message = params["message"]
		message = a 
		 notification = Grocer::Notification.new(
	    device_token:      device.device_token,
	    alert:             message,
	    badge:             3,
	    sound:             "siren.aiff",         # optional
	    expiry:            Time.now + 60*60,     # optional; 0 is default, meaning the message is not stored
	    identifier:        c                 # optional
	    # content_available: true                  # optional; any truthy value will set 'content-available' to 1
	  )
	  

	  

	 if pusher.push(notification)
	 	render :json=> {:status => true}
	 else
		render :json=> {:status => false}
	 end
	end

	 feedback.each do |attempt|
	    puts "Device #{attempt.device_token} failed at #{attempt.timestamp}"
	 end
end
```

**Comment by stevenharman** [comment]
Hello @alifjamaluddin. I'm going to close this Issue due to inactivity. Please re-open it if you are still experiencing the problem and/or have more information to add.

Thank you!
