### ISSUE TITLE
Errno::EPIPE: Broken pipe

### ISSUE THREAD

**Issue by jyoti2shine** [grocer/grocer#113]
Hi Team,

I am trying to send notifications to multiple devices , but it fails and throws the error below:

```
Errno::EPIPE: Broken pipe
    from /Users/mohantysan/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/openssl/buffering.rb:318:in `syswrite'
    from /Users/mohantysan/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/openssl/buffering.rb:318:in `do_write'
    from /Users/mohantysan/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/openssl/buffering.rb:336:in `write'
    from /Users/mohantysan/.rvm/gems/ruby-1.9.3-p362@echo/gems/grocer-0.6.1/lib/grocer/connection.rb:24:in `block in write'
    from /Users/mohantysan/.rvm/gems/ruby-1.9.3-p362@echo/gems/grocer-0.6.1/lib/grocer/connection.rb:56:in `with_connection'
    from /Users/mohantysan/.rvm/gems/ruby-1.9.3-p362@echo/gems/grocer-0.6.1/lib/grocer/connection.rb:23:in `write'
    from /Users/mohantysan/.rvm/gems/ruby-1.9.3-p362@echo/gems/grocer-0.6.1/lib/grocer/pusher.rb:8:in `push'
```

Code:

``` ruby
notifications = Array.new
message = am.message.body
am.app.devices.find_each(:batch_size => 1000) do |device|
  notification = Grocer::Notification.new(
    device_token:      device.token,
    alert:             message,
    badge:             42,
    sound:             "siren.aiff",         # optional
    expiry:            Time.now + 60*60,     # optional; 0 is default, meaning the message is not stored
    content_available: true                  # optional; any truthy value will set 'content-available' to 1
  )
  notifications << notification
end

puts pusher = Grocer.pusher(
  certificate: "/Users/mohantysan/Documents/Certificates/SecureApp.pem",      # required
  passphrase:  "",                       # optional
  gateway:     "gateway.sandbox.push.apple.com", # optional; See note below.
  port:        2195,                     # optional
  retries:     1                         # optional
)

notifications.flatten.each do |notification|
  puts notification.inspect
  puts pusher.push(notification)
end
```

**Comment by stevenharman** [comment]
Can you also check the `Feedback` channel and see if any errors are being returned? Perhaps you're sending a flood of invalid notifications and so Apple is closing the connection and then blocking you?

**Comment by stevenharman** [comment]
@jyoti2shine Any updates? I'm going to close due to inactivity, but please re-open if you have more info.
